/*
 * Copyright 2026 Duck Apps Contributor
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.eltavine.duckdetector.buildlogic

import com.android.build.api.variant.ApplicationAndroidComponentsExtension
import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.getByType
import org.gradle.kotlin.dsl.register

/** The name under which every detector's ui layer exports its dashboard card. */
const val DETECTOR_CARD_PROPERTY: String = "detectorFeature"

/**
 * Writes `detectorCards`, the dashboard card of every detector unit, into the application's sources.
 *
 * Each detector's ui layer exports its card as `detectorFeature` in
 * `com.eltavine.duckdetector.features.<name>.ui`, so the list follows from the directory layout and
 * the application names no detector to show its card. The list is in directory order; the
 * application orders its cards by `DetectorCatalog`.
 */
@CacheableTask
abstract class GenerateDetectorCardsTask : DefaultTask() {

    /** The detector units, by directory name. */
    @get:Input
    abstract val units: ListProperty<String>

    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val root = outputDirectory.get().asFile
        root.deleteRecursively()
        val directory = root.resolve(packageName.get().replace('.', '/')).apply { mkdirs() }
        directory.resolve("DetectorCards.kt").writeText(
            buildString {
                appendLine("// Generated by GenerateDetectorCardsTask from every feature/<name>/ui module; do not edit.")
                appendLine("package ${packageName.get()}")
                appendLine()
                appendLine("import com.eltavine.duckdetector.core.ui.detector.DetectorFeature")
                appendLine()
                appendLine("/** The dashboard card of every detector, in directory order. */")
                appendLine("internal val detectorCards: List<DetectorFeature> = listOf(")
                units.get().forEach { unit ->
                    appendLine("    com.eltavine.duckdetector.features.$unit.ui.$DETECTOR_CARD_PROPERTY,")
                }
                appendLine(")")
            },
        )
    }
}

/** Generates `detectorCards` into [packageName] for every variant of this application. */
fun Project.generateDetectorCards(packageName: String) {
    val generate = tasks.register<GenerateDetectorCardsTask>("generateDetectorCards") {
        units.set(detectorModules("ui").map { path -> path.split(':')[2] })
        this.packageName.set(packageName)
        outputDirectory.set(layout.buildDirectory.dir("generated/source/detectorCards"))
    }
    extensions.getByType<ApplicationAndroidComponentsExtension>().onVariants { variant ->
        variant.sources.kotlin?.addGeneratedSourceDirectory(generate, GenerateDetectorCardsTask::outputDirectory)
    }
}
